tools:
  - tool_square_id: "seniverse"
    name: "心知天气"
    desc: "心知天气是北京心知科技有限公司旗下的国内领先商业气象服务平台，通过天气 API、BI、数据分析服务等为能源、交通、农业等多个行业提供天气和行业解决方案。"
    avatar_path: "tool/seniverse/logo.png"
    detail: "心知天气是北京心知科技有限公司旗下的国内领先商业气象服务平台心知天气是北京心知科技有限公司旗下的国内领先商业气象服务平台。可前往 https://www.seniverse.com/ 申请API Key"
    tags: ""
    need_api_key_input: true
    auth_type: "api_key_query"
    api_key_header_prefix: ""
    api_key_header: ""
    api_key_query_param: "key"
    api_key_value: ""
    schema: ""
    schema_path: "tool/seniverse/openapi.json"
  - tool_square_id: "qwenimage20b"
    name: "Qwen-Image-20B"
    desc: "Qwen-Image文生图大模型，通义出品，参数量20B，支持中英文图像生成，拥有出色的文字渲染能力。"
    avatar_path: "tool/qwenimage20b/logo.png"
    detail: "Qwen-Image文生图大模型，通义出品，参数量20B，支持中英文图像生成，拥有出色的文字渲染能力。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
    tags: "Qwen-Image,文生图,8K"
    need_api_key_input: true
    auth_type: "api_key_header"
    api_key_header_prefix: "bearer"
    api_key_header: "Authorization"
    api_key_query_param: ""
    api_key_value: ""
    schema: ""
    schema_path: "tool/qwenimage20b/openapi.json"
  - tool_square_id: "bochawebsearch"
    name: "博查AI搜索"
    desc: "博查AI搜索是一个基于大模型和实时搜索技术的答案引擎。你可以用自然语言提问，它会理解问题、细分检索并直接生成准确的答案。"
    avatar_path: "tool/bochawebsearch/logo.png"
    detail: "从近百亿网页和生态内容源中搜索高质量世界知识，例如新闻、图片、百科、文库等。可前往 https://open.bochaai.com/ 申请API Key"
    tags: ""
    need_api_key_input: true
    auth_type: "api_key_header"
    api_key_header_prefix: "bearer"
    api_key_header: "Authorization"
    api_key_query_param: ""
    api_key_value: ""
    schema: ""
    schema_path: "tool/bochawebsearch/openapi.json"
  - tool_square_id: "yuanjingtexttoimage12b"
    name: "元景-文生图-12B"
    desc: "元景-文生图-12B文生图大模型基于扩散模型机制训练，支持中英双语输入，能够根据输入内容生成符合描述的图像内容，并增加意图去除和提示词润色。"
    avatar_path: "tool/yuanjingtexttoimage12b/logo.png"
    detail: " 元景-文生图-12B基于扩散模型机制自研，能够根据输入的文本生成语义接近的图像，支持中英双语输入，在通用文生图能力基础上增加了意图去除和提示词润色。如，提示词为“画一个乌龟”，则提取并润色出“一个乌龟在沙滩上爬行”后生成图片。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
    tags: "元景-1.0,文生图"
    need_api_key_input: true
    auth_type: "api_key_header"
    api_key_header_prefix: "bearer"
    api_key_header: "Authorization"
    api_key_query_param: ""
    api_key_value: ""
    schema: ""
    schema_path: "tool/yuanjingtexttoimage12b/openapi.json"
  - tool_square_id: "yuanjingimg2img12b"
    name: "元景-图生图-12B"
    desc: "元景-图生图-12B接口，基于用户上传的图像，生成指定风格的图像"
    avatar_path: "tool/yuanjingimg2img12b/logo.png"
    detail: "元景-图生图-12B接口，能将输入图片转换成指定风格。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
    tags: ""
    need_api_key_input: true
    auth_type: "api_key_header"
    api_key_header_prefix: "bearer"
    api_key_header: "Authorization"
    api_key_query_param: ""
    api_key_value: ""
    schema: ""
    schema_path: "tool/yuanjingimg2img12b/openapi.json"
#  - tool_square_id: "yuanjingaudiofile2text1p0"
#    name: "元景-文件语音识别1.0"
#    desc: "支持中英文等多种语言长短音频文件的识别。"
#    avatar_path: "tool/yuanjingaudiofile2text1p0/logo.png"
#    detail: "支持的音频格式： wav、m4a、mp3、mp4、acc等。长音频建议调用异步接口上传音频，再通过查询接口获取转写结果。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
#    tags: "自动语音识别"
#    need_api_key_input: false
#    auth_type: "none"
#    api_key_header_prefix: ""
#    api_key_header: ""
#    api_key_query_param: ""
#    api_key_value: ""
#    schema: ""
#    schema_path: "tool/yuanjingaudiofile2text1p0/openapi.json"
  - tool_square_id: "yuanjingimgs2video"
    name: "元景-首尾帧图生视频生成-14B"
    desc: "元景-首尾帧图生视频-14B，根据上传的两张首尾帧图片生成视频。"
    avatar_path: "tool/yuanjingimgs2video/logo.png"
    detail: "注意服务在接收到请求时，会立即返回视频resourceId，但视频制作需要一定时间。获取视频需要通过返回的resourceId向首尾帧视频获取服务发请求，建议每分钟请求一次。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
    tags: "图生视频"
    need_api_key_input: true
    auth_type: "api_key_header"
    api_key_header_prefix: "bearer"
    api_key_header: "Authorization"
    api_key_query_param: ""
    api_key_value: ""
    schema: ""
    schema_path: "tool/yuanjingimgs2video/openapi.json"
  - tool_square_id: "yuanjingimgs2videoget"
    name: "元景-首尾帧图生视频获取-14B"
    desc: "联通元景多模态首尾帧视频结果获取接口。"
    avatar_path: "tool/yuanjingimgs2videoget/logo.png"
    detail: "根据输入的首尾帧图片生成视频。视频生成服务在接收到请求时，会立即返回视频名，但视频制作需要一定时间。获取视频需要通过返回的视频名（resourceId 字段）向视频获取服务发起请求，建议每分钟请求一次。首尾帧视频生成服务接口见元景-首尾帧图生视频生成-14B。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
    tags: ""
    need_api_key_input: true
    auth_type: "api_key_header"
    api_key_header_prefix: "bearer"
    api_key_header: "Authorization"
    api_key_query_param: ""
    api_key_value: ""
    schema: ""
    schema_path: "tool/yuanjingimgs2videoget/openapi.json"
  - tool_square_id: "yuanjingimagesearchtextsearch"
    name: "元景-以文搜图"
    desc: "根据输入的文本描述搜索相关的图片。仅支持行\"人\"和\"机动车\"。"
    avatar_path: "tool/yuanjingimagesearchtextsearch/logo.png"
    detail: "输入一张或多张查询图片，系统自动检测并抠取图片中的人或车辆目标，提取其多模态特征，与图库中已入库的图像特征进行相似度检索，返回最相似的候选图片及相似度分数。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
    tags: ""
    need_api_key_input: true
    auth_type: "api_key_header"
    api_key_header_prefix: "bearer"
    api_key_header: "Authorization"
    api_key_query_param: ""
    api_key_value: ""
    schema: ""
    schema_path: "tool/yuanjingimagesearchtextsearch/openapi.json"
  - tool_square_id: "yuanjingimagesearchimagesearch"
    name: "元景-以图搜图"
    desc: "根据输入的图片搜索相关的图片。仅支持行\"人\"和\"机动车\"。"
    avatar_path: "tool/yuanjingimagesearchimagesearch/logo.png"
    detail: "输入一张或多张查询图片，系统自动检测并抠取图片中的人或车辆目标，提取其多模态特征，与图库中已入库的图像特征进行相似度检索，返回最相似的候选图片及相似度分数。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
    tags: ""
    need_api_key_input: true
    auth_type: "api_key_header"
    api_key_header_prefix: "bearer"
    api_key_header: "Authorization"
    api_key_query_param: ""
    api_key_value: ""
    schema: ""
    schema_path: "tool/yuanjingimagesearchimagesearch/openapi.json"
  - tool_square_id: "yuanjingimagesearchimageinsert"
    name: "元景-图片入库"
    desc: "将图片数据批量导入向量数据库，用于后续的图像检索任务。目前只支持行\"人\"和\"机动车\"的目标检测和特征提取。"
    avatar_path: "tool/yuanjingimagesearchimageinsert/logo.png"
    detail: "系统将自动对图片进行检测、抠图，并提取目标区域（如行人、机动车）的视觉特征后入库。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
    tags: ""
    need_api_key_input: true
    auth_type: "api_key_header"
    api_key_header_prefix: "bearer"
    api_key_header: "Authorization"
    api_key_query_param: ""
    api_key_value: ""
    schema: ""
    schema_path: "tool/yuanjingimagesearchimageinsert/openapi.json"
  - tool_square_id: "fileurlconvertbase64"
    name: "文件URL转Base64"
    desc: "将文件URL转换为base64格式数据"
    avatar_path: "tool/fileurlconvertbase64/logo.png"
    detail: "支持将各种文件类型的URL转换为base64格式数据，便于前端直接显示和处理"
    tags: ""
    need_api_key_input: false
    auth_type: "none"
    api_key_header_prefix: ""
    api_key_header: ""
    api_key_query_param: ""
    api_key_value: ""
    schema: ""
    schema_path: "tool/fileurlconvertbase64/openapi.json"
  - tool_square_id: "uploadfilebybase64"
    name: "Base64文件上传"
    desc: "通过Base64格式上传文件到服务器，返回文件访问链接"
    avatar_path: "tool/uploadfilebybase64/logo.png"
    detail: "支持通过Base64编码格式上传各种类型的文件，返回文件的URL访问地址和URI路径"
    tags: ""
    need_api_key_input: false
    auth_type: "none"
    api_key_header_prefix: ""
    api_key_header: ""
    api_key_query_param: ""
    api_key_value: ""
    schema: ""
    schema_path: "tool/uploadfilebybase64/openapi.json"