tools:
  - tool_square_id: "seniverse"
    name: "心知天气"
    desc: "心知天气是北京心知科技有限公司旗下的国内领先商业气象服务平台，通过天气 API、BI、数据分析服务等为能源、交通、农业等多个行业提供天气和行业解决方案。"
    avatar_path: "seniverse/logo.png"
    detail: "心知天气是北京心知科技有限公司旗下的国内领先商业气象服务平台心知天气是北京心知科技有限公司旗下的国内领先商业气象服务平台。可前往 https://www.seniverse.com/ 申请API Key"
    tags: ""
    need_api_key_input: true
    type: "API Key"
    auth_type: "Custom"
    custom_header_name: "key"
    api_key: ""
    schema: ""
    schema_path: "seniverse/openapi.json"
    tools:
      - name: "seniverse_current_weather"
        description: "获取指定城市的天气实况。"
        input_schema:
          type: object
          properties:
            - field: "key"
              type: "string"
              description: "你的 API 密钥"
            - field: "location"
              type: "string"
              description: "所查询的位置"
            - field: "language"
              type: "string"
              description: "语言"
            - field: "unit"
              type: "string"
              description: "单位"
      - name: "seniverse_day_to_day_weather"
        description: "获取指定城市未来最多 3天每天的白天和夜间预报天气。"
        input_schema:
          type: object
          properties:
            - field: "key"
              type: "string"
              description: "你的 API 密钥"
            - field: "location"
              type: "string"
              description: "所查询的位置"
            - field: "language"
              type: "string"
              description: "语言"
            - field: "unit"
              type: "string"
              description: "单位"
            - field: "start"
              type: "string"
              description: "起始时间"
            - field: "days"
              type: "string"
              description: "天数"
          required:
            - "key"
            - "location"
      - name: "seniverse_life_index"
        description: "获取指定城市的基本、交通、生活、运动、健康 5 大类共 27 项生活指数，预测至未来5天，仅支持中国城市。"
        input_schema:
          type: object
          properties:
            - field: "key"
              type: "string"
              description: "你的 API 密钥"
            - field: "location"
              type: "string"
              description: "所查询的位置"
            - field: "language"
              type: "string"
              description: "语言"
            - field: "days"
              type: "string"
              description: "天数"
          required:
            - "key"
            - "location"
      - name: "seniverse_city_search"
        description: "根据城市ID、中文、英文、拼音、IP、经纬度搜索匹配的城市。"
        input_schema:
          type: object
          properties:
            - field: "key"
              type: "string"
              description: "你的API密钥"
            - field: "q"
              type: "array"
              description: "所查询的位置"
            - field: "limit"
              type: "string"
              description: "分页每页最多记录数"
            - field: "offset"
              type: "string"
              description: "跳过的记录数 (可选) 配合limit参数实现分页"
          required:
            - "key"
            - "q"
  - tool_square_id: "yuanjingtexttoimage12b"
    name: "元景-文生图-12B"
    desc: "元景-文生图-12B文生图大模型基于扩散模型机制训练，支持中英双语输入，能够根据输入内容生成符合描述的图像内容，并增加意图去除和提示词润色。"
    avatar_path: "yuanjingtexttoimage12b/logo.png"
    detail: " 元景-文生图-12B基于扩散模型机制自研，能够根据输入的文本生成语义接近的图像，支持中英双语输入，在通用文生图能力基础上增加了意图去除和提示词润色。如，提示词为“画一个乌龟”，则提取并润色出“一个乌龟在沙滩上爬行”后生成图片。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
    tags: "元景-1.0,文生图"
    need_api_key_input: true
    type: "API Key"
    auth_type: "Custom"
    custom_header_name: "key"
    api_key: ""
    schema: ""
    schema_path: "yuanjingtexttoimage12b/openapi.json"
    tools:
      - name: "yuanjing_text2img_12b"
        description: ""
        input_schema:
          type: object
          properties:
            - field: "prompt"
              type: "string"
              description: "提示词"
            - field: "advanced_opt"
              type: "string"
              description: "高级选项参数，为JSON格式字符串，包含生成图像的高度、宽度、数量、负提示词和风格等参数"
            - field: "response_format"
              type: "string"
              description: "url or b64_json, 默认b64_json"
            - field: "report_url"
              type: "string"
              description: "参考 http://192.168.2.109:4999/web/#/611659092/216556697，默认https://test.ai-yuanjing.com/bffservice/v1/inference/report"
          required:
            - "prompt"
  - tool_square_id: "qwenimage20b"
    name: "Qwen-Image-20B"
    desc: "Qwen-Image文生图大模型，通义出品，参数量20B，支持中英文图像生成，拥有出色的文字渲染能力。"
    avatar_path: "qwenimage20b/logo.png"
    detail: "Qwen-Image文生图大模型，通义出品，参数量20B，支持中英文图像生成，拥有出色的文字渲染能力。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
    tags: "Qwen-Image,文生图,8K"
    need_api_key_input: true
    type: "API Key"
    auth_type: "Custom"
    custom_header_name: "key"
    api_key: ""
    schema: ""
    schema_path: "qwenimage20b/openapi.json"
    tools:
      - name: "qwen_text2img_20b"
        description: ""
        input_schema:
          type: object
          properties:
            - field: "model"
              type: "string"
              description: "模型ID"
            - field: "prompt"
              type: "string"
              description: "提示词"
            - field: "report_url"
              type: "string"
              description: "参考，http://192.168.2.109:4999/web/#/611659092/216556697"
            - field: "n"
              type: "Integer"
              description: "生成图片张数,最大为2,超过2自动被处理为2"
            - field: "size"
              type: "string"
              description: "生成图片的分辨率，格式为 {width}x{height}。由于模型适用范围有限，输入尺寸会根据长宽比自动调整为模型最佳输出分辨率"
            - field: "response_format"
              type: "string"
              description: "返回格式，b64_json 或者url. 不合法响应格式默认处理为b64_json"
          required:
            - "prompt"
  - tool_square_id: "yuanjingimg2img12b"
    name: "元景-图生图-12B"
    desc: "元景-图生图-12B接口，基于用户上传的图像，生成指定风格的图像"
    avatar_path: "yuanjingimg2img12b/logo.png"
    detail: "元景-图生图-12B接口，能将输入图片转换成指定风格。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
    tags: ""
    need_api_key_input: true
    type: "API Key"
    auth_type: "Custom"
    custom_header_name: "key"
    api_key: ""
    schema: ""
    schema_path: "yuanjingimg2img12b/openapi.json"
    tools:
      - name: "yuanjing_img2img_12b"
        description: "元景-图生图-12B接口，基于用户上传的图像，生成指定风格的图像。"
        input_schema:
          type: object
          properties:
            - field: "image"
              type: "string"
              description: "base64编码的图像字符串"
            - field: "style"
              type: "string"
              description: "图片风格，目前支持吉卜力"
            - field: "prompt"
              type: "string"
              description: "提示信息，预留接口，不生效"
          required:
            - "image"
            - "style"
  - tool_square_id: "yuanjingaudiofile2text1p0"
    name: "元景-文件语音识别1.0"
    desc: "支持中英文等多种语言长短音频文件的识别。"
    avatar_path: "yuanjingaudiofile2text1p0/logo.png"
    detail: "支持的音频格式： wav、m4a、mp3、mp4、acc等。长音频建议调用异步接口上传音频，再通过查询接口获取转写结果。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
    tags: "自动语音识别"
    need_api_key_input: true
    type: "API Key"
    auth_type: "Custom"
    custom_header_name: "key"
    api_key: ""
    schema: ""
    schema_path: "yuanjingaudiofile2text1p0/openapi.json"
    tools:
      - name: "yuanjing_audiofile2text_1p0"
        description: "支持中英文等多种语言长短音频文件的识别。"
        input_schema:
          type: object
          properties:
            - field: "config"
              type: "string"
              description: "配置数据。"
            - field: "file"
              type: "string"
              description: "音频文件"
          required:
            - "config"
            - "file"
  - tool_square_id: "yuanjingimgs2video"
    name: "元景-首尾帧图生视频生成-14B"
    desc: "元景-首尾帧图生视频-14B，根据上传的两张首尾帧图片生成视频。"
    avatar_path: "yuanjingimgs2video/logo.png"
    detail: "注意服务在接收到请求时，会立即返回视频resourceId，但视频制作需要一定时间。获取视频需要通过返回的resourceId向首尾帧视频获取服务发请求，建议每分钟请求一次。可前往 https://maas.ai-yuanjing.com/ 申请API Key"
    tags: "图生视频"
    need_api_key_input: true
    type: "API Key"
    auth_type: "Custom"
    custom_header_name: "key"
    api_key: ""
    schema: ""
    schema_path: "yuanjingimgs2video/openapi.json"
    tools:
      - name: "yuanjing_imgs2video"
        description: "元景-首尾帧图生视频-14B，根据上传的两张首尾帧图片生成视频。"
        input_schema:
          type: object
          properties:
            - field: "images"
              type: "array"
              description: "首帧和尾帧对应的图像字符串，base64编码"
            - field: "query"
              type: "string"
              description: "用户提出的问题或提示语。区别于已有的prompt"
            - field: "session_id"
              type: "string"
              description: "请求的对话窗口id"
            - field: "request_id"
              type: "string"
              description: "用户每轮请求问题对应的唯一id"
            - field: "userId"
              type: "string"
              description: "用户id"
            - field: "prompt"
              type: "string"
              description: "提示词"
          required:
            - "images"
  - tool_square_id: "bochawebsearch"
    name: "博查AI搜索"
    desc: "博查AI搜索是一个基于大模型和实时搜索技术的答案引擎。你可以用自然语言提问，它会理解问题、细分检索并直接生成准确的答案。"
    avatar_path: "bochawebsearch/logo.png"
    detail: "从近百亿网页和生态内容源中搜索高质量世界知识，例如新闻、图片、百科、文库等。可前往 https://open.bochaai.com/ 申请API Key"
    tags: ""
    need_api_key_input: true
    type: "API Key"
    auth_type: "Custom"
    custom_header_name: "key"
    api_key: ""
    schema: ""
    schema_path: "bochawebsearch/openapi.json"
    tools:
      - name: "bochaWebSearch"
        description: "从全网搜索任何网页信息和网页链接，结果准确、摘要完整，更适合AI使用。"
        input_schema:
          type: object
          properties:
            - field: "query"
              type: "string"
              description: "搜索关键字或语句"
            - field: "summary"
              type: "boolean"
              description: "是否在搜索结果中包含摘要"
            - field: "freshness"
              type: "string"
              description: "搜索指定时间范围内的网页（可选值 \"noLimit\"、\"oneDay\"、\"oneWeek\"、\"oneMonth\"、\"oneYear\"）"
            - field: "count"
              type: "integer"
              description: "返回的搜索结果数量（1-8），默认为8"
          required:
            - "query"
            - "count"